spring:
  datasource:
    url: jdbc:postgresql://211.222.25.101:5432/ATteampro
    username: ATproject3
    password: at1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: false
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
